apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dys-backend-ingress
  annotations:
    kubernetes.io/ingress.class: gce
    kubernetes.io/ingress.global-static-ip-name: dys-backend-ip
    # HTTPS 리다이렉트 설정
    kubernetes.io/ingress.allow-http: "false"
spec:
  tls:
  - secretName: dys-backend-tls
  rules:
  - host: 34.64.136.237.nip.io  # 또는 실제 도메인
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dys-backend-service
            port:
              number: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: dys-backend-service
spec:
  selector:
    app: dys-backend
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP
